using BusinessObject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infrastructure.FluentAPI
{
    public class CountryConfiguration : IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> builder)
        {
            builder.HasData(
                new Country { CountryId = 1, CountryName = "Andorra" },
                new Country { CountryId = 2, CountryName = "United Arab Emirates" },
                new Country { CountryId = 3, CountryName = "Afghanistan" },
                new Country { CountryId = 4, CountryName = "Antigua and Barbuda" },
                new Country { CountryId = 5, CountryName = "Anguilla" },
                new Country { CountryId = 6, CountryName = "Albania" },
                new Country { CountryId = 7, CountryName = "Armenia" },
                new Country { CountryId = 8, CountryName = "Angola" },
                new Country { CountryId = 9, CountryName = "Antarctica" },
                new Country { CountryId = 10, CountryName = "Argentina" },
                new Country { CountryId = 11, CountryName = "American Samoa" },
                new Country { CountryId = 12, CountryName = "Austria" },
                new Country { CountryId = 13, CountryName = "Australia" },
                new Country { CountryId = 14, CountryName = "Aruba" },
                new Country { CountryId = 15, CountryName = "Åland" },
                new Country { CountryId = 16, CountryName = "Azerbaijan" },
                new Country { CountryId = 17, CountryName = "Bosnia and Herzegovina" },
                new Country { CountryId = 18, CountryName = "Barbados" },
                new Country { CountryId = 19, CountryName = "Bangladesh" },
                new Country { CountryId = 20, CountryName = "Belgium" },
                new Country { CountryId = 21, CountryName = "Burkina Faso" },
                new Country { CountryId = 22, CountryName = "Bulgaria" },
                new Country { CountryId = 23, CountryName = "Bahrain" },
                new Country { CountryId = 24, CountryName = "Burundi" },
                new Country { CountryId = 25, CountryName = "Benin" },
                new Country { CountryId = 26, CountryName = "Saint Barthélemy" },
                new Country { CountryId = 27, CountryName = "Bermuda" },
                new Country { CountryId = 28, CountryName = "Brunei" },
                new Country { CountryId = 29, CountryName = "Bolivia" },
                new Country { CountryId = 30, CountryName = "Bonaire, Sint Eustatius, and Saba" },
                new Country { CountryId = 31, CountryName = "Brazil" },
                new Country { CountryId = 32, CountryName = "Bahamas" },
                new Country { CountryId = 33, CountryName = "Bhutan" },
                new Country { CountryId = 34, CountryName = "Bouvet Island" },
                new Country { CountryId = 35, CountryName = "Botswana" },
                new Country { CountryId = 36, CountryName = "Belarus" },
                new Country { CountryId = 37, CountryName = "Belize" },
                new Country { CountryId = 38, CountryName = "Canada" },
                new Country { CountryId = 39, CountryName = "Cocos (Keeling) Islands" },
                new Country { CountryId = 40, CountryName = "DR Congo" },
                new Country { CountryId = 41, CountryName = "Central African Republic" },
                new Country { CountryId = 42, CountryName = "Congo Republic" },
                new Country { CountryId = 43, CountryName = "Switzerland" },
                new Country { CountryId = 44, CountryName = "Ivory Coast" },
                new Country { CountryId = 45, CountryName = "Cook Islands" },
                new Country { CountryId = 46, CountryName = "Chile" },
                new Country { CountryId = 47, CountryName = "Cameroon" },
                new Country { CountryId = 48, CountryName = "China" },
                new Country { CountryId = 49, CountryName = "Colombia" },
                new Country { CountryId = 50, CountryName = "Costa Rica" },
                new Country { CountryId = 51, CountryName = "Cuba" },
                new Country { CountryId = 52, CountryName = "Cabo Verde" },
                new Country { CountryId = 53, CountryName = "Curaçao" },
                new Country { CountryId = 54, CountryName = "Christmas Island" },
                new Country { CountryId = 55, CountryName = "Cyprus" },
                new Country { CountryId = 56, CountryName = "Czechia" },
                new Country { CountryId = 57, CountryName = "Germany" },
                new Country { CountryId = 58, CountryName = "Djibouti" },
                new Country { CountryId = 59, CountryName = "Denmark" },
                new Country { CountryId = 60, CountryName = "Dominica" },
                new Country { CountryId = 61, CountryName = "Dominican Republic" },
                new Country { CountryId = 62, CountryName = "Algeria" },
                new Country { CountryId = 63, CountryName = "Ecuador" },
                new Country { CountryId = 64, CountryName = "Estonia" },
                new Country { CountryId = 65, CountryName = "Egypt" },
                new Country { CountryId = 66, CountryName = "Western Sahara" },
                new Country { CountryId = 67, CountryName = "Eritrea" },
                new Country { CountryId = 68, CountryName = "Spain" },
                new Country { CountryId = 69, CountryName = "Ethiopia" },
                new Country { CountryId = 70, CountryName = "Finland" },
                new Country { CountryId = 71, CountryName = "Fiji" },
                new Country { CountryId = 72, CountryName = "Falkland Islands" },
                new Country { CountryId = 73, CountryName = "Micronesia" },
                new Country { CountryId = 74, CountryName = "Faroe Islands" },
                new Country { CountryId = 75, CountryName = "France" },
                new Country { CountryId = 76, CountryName = "Gabon" },
                new Country { CountryId = 77, CountryName = "United Kingdom" },
                new Country { CountryId = 78, CountryName = "Grenada" },
                new Country { CountryId = 79, CountryName = "Georgia" },
                new Country { CountryId = 80, CountryName = "French Guiana" },
                new Country { CountryId = 81, CountryName = "Guernsey" },
                new Country { CountryId = 82, CountryName = "Ghana" },
                new Country { CountryId = 83, CountryName = "Gibraltar" },
                new Country { CountryId = 84, CountryName = "Greenland" },
                new Country { CountryId = 85, CountryName = "The Gambia" },
                new Country { CountryId = 86, CountryName = "Guinea" },
                new Country { CountryId = 87, CountryName = "Guadeloupe" },
                new Country { CountryId = 88, CountryName = "Equatorial Guinea" },
                new Country { CountryId = 89, CountryName = "Greece" },
                new Country { CountryId = 90, CountryName = "South Georgia and South Sandwich Islands" },
                new Country { CountryId = 91, CountryName = "Guatemala" },
                new Country { CountryId = 92, CountryName = "Guam" },
                new Country { CountryId = 93, CountryName = "Guinea-Bissau" },
                new Country { CountryId = 94, CountryName = "Guyana" },
                new Country { CountryId = 95, CountryName = "Hong Kong" },
                new Country { CountryId = 96, CountryName = "Heard and McDonald Islands" },
                new Country { CountryId = 97, CountryName = "Honduras" },
                new Country { CountryId = 98, CountryName = "Croatia" },
                new Country { CountryId = 99, CountryName = "Haiti" },
                new Country { CountryId = 100, CountryName = "Hungary" },
                new Country { CountryId = 101, CountryName = "Indonesia" },
                new Country { CountryId = 102, CountryName = "Ireland" },
                new Country { CountryId = 103, CountryName = "Israel" },
                new Country { CountryId = 104, CountryName = "Isle of Man" },
                new Country { CountryId = 105, CountryName = "India" },
                new Country { CountryId = 106, CountryName = "British Indian Ocean Territory" },
                new Country { CountryId = 107, CountryName = "Iraq" },
                new Country { CountryId = 108, CountryName = "Iran" },
                new Country { CountryId = 109, CountryName = "Iceland" },
                new Country { CountryId = 110, CountryName = "Italy" },
                new Country { CountryId = 111, CountryName = "Jersey" },
                new Country { CountryId = 112, CountryName = "Jamaica" },
                new Country { CountryId = 113, CountryName = "Jordan" },
                new Country { CountryId = 114, CountryName = "Japan" },
                new Country { CountryId = 115, CountryName = "Kenya" },
                new Country { CountryId = 116, CountryName = "Kyrgyzstan" },
                new Country { CountryId = 117, CountryName = "Cambodia" },
                new Country { CountryId = 118, CountryName = "Kiribati" },
                new Country { CountryId = 119, CountryName = "Comoros" },
                new Country { CountryId = 120, CountryName = "St Kitts and Nevis" },
                new Country { CountryId = 121, CountryName = "North Korea" },
                new Country { CountryId = 122, CountryName = "South Korea" },
                new Country { CountryId = 123, CountryName = "Kuwait" },
                new Country { CountryId = 124, CountryName = "Cayman Islands" },
                new Country { CountryId = 125, CountryName = "Kazakhstan" },
                new Country { CountryId = 126, CountryName = "Laos" },
                new Country { CountryId = 127, CountryName = "Lebanon" },
                new Country { CountryId = 128, CountryName = "Saint Lucia" },
                new Country { CountryId = 129, CountryName = "Liechtenstein" },
                new Country { CountryId = 130, CountryName = "Sri Lanka" },
                new Country { CountryId = 131, CountryName = "Liberia" },
                new Country { CountryId = 132, CountryName = "Lesotho" },
                new Country { CountryId = 133, CountryName = "Lithuania" },
                new Country { CountryId = 134, CountryName = "Luxembourg" },
                new Country { CountryId = 135, CountryName = "Latvia" },
                new Country { CountryId = 136, CountryName = "Libya" },
                new Country { CountryId = 137, CountryName = "Morocco" },
                new Country { CountryId = 138, CountryName = "Monaco" },
                new Country { CountryId = 139, CountryName = "Moldova" },
                new Country { CountryId = 140, CountryName = "Montenegro" },
                new Country { CountryId = 141, CountryName = "Saint Martin" },
                new Country { CountryId = 142, CountryName = "Madagascar" },
                new Country { CountryId = 143, CountryName = "Marshall Islands" },
                new Country { CountryId = 144, CountryName = "North Macedonia" },
                new Country { CountryId = 145, CountryName = "Mali" },
                new Country { CountryId = 146, CountryName = "Myanmar" },
                new Country { CountryId = 147, CountryName = "Mongolia" },
                new Country { CountryId = 148, CountryName = "Macao" },
                new Country { CountryId = 149, CountryName = "Northern Mariana Islands" },
                new Country { CountryId = 150, CountryName = "Martinique" },
                new Country { CountryId = 151, CountryName = "Mauritania" },
                new Country { CountryId = 152, CountryName = "Montserrat" },
                new Country { CountryId = 153, CountryName = "Malta" },
                new Country { CountryId = 154, CountryName = "Mauritius" },
                new Country { CountryId = 155, CountryName = "Maldives" },
                new Country { CountryId = 156, CountryName = "Malawi" },
                new Country { CountryId = 157, CountryName = "Mexico" },
                new Country { CountryId = 158, CountryName = "Malaysia" },
                new Country { CountryId = 159, CountryName = "Mozambique" },
                new Country { CountryId = 160, CountryName = "Namibia" },
                new Country { CountryId = 161, CountryName = "New Caledonia" },
                new Country { CountryId = 162, CountryName = "Niger" },
                new Country { CountryId = 163, CountryName = "Norfolk Island" },
                new Country { CountryId = 164, CountryName = "Nigeria" },
                new Country { CountryId = 165, CountryName = "Nicaragua" },
                new Country { CountryId = 166, CountryName = "Netherlands" },
                new Country { CountryId = 167, CountryName = "Norway" },
                new Country { CountryId = 168, CountryName = "Nepal" },
                new Country { CountryId = 169, CountryName = "Nauru" },
                new Country { CountryId = 170, CountryName = "Niue" },
                new Country { CountryId = 171, CountryName = "New Zealand" },
                new Country { CountryId = 172, CountryName = "Oman" },
                new Country { CountryId = 173, CountryName = "Panama" },
                new Country { CountryId = 174, CountryName = "Peru" },
                new Country { CountryId = 175, CountryName = "French Polynesia" },
                new Country { CountryId = 176, CountryName = "Papua New Guinea" },
                new Country { CountryId = 177, CountryName = "Philippines" },
                new Country { CountryId = 178, CountryName = "Pakistan" },
                new Country { CountryId = 179, CountryName = "Poland" },
                new Country { CountryId = 180, CountryName = "Saint Pierre and Miquelon" },
                new Country { CountryId = 181, CountryName = "Pitcairn Islands" },
                new Country { CountryId = 182, CountryName = "Puerto Rico" },
                new Country { CountryId = 183, CountryName = "Palestine" },
                new Country { CountryId = 184, CountryName = "Portugal" },
                new Country { CountryId = 185, CountryName = "Palau" },
                new Country { CountryId = 186, CountryName = "Paraguay" },
                new Country { CountryId = 187, CountryName = "Qatar" },
                new Country { CountryId = 188, CountryName = "Réunion" },
                new Country { CountryId = 189, CountryName = "Romania" },
                new Country { CountryId = 190, CountryName = "Serbia" },
                new Country { CountryId = 191, CountryName = "Russia" },
                new Country { CountryId = 192, CountryName = "Rwanda" },
                new Country { CountryId = 193, CountryName = "Saudi Arabia" },
                new Country { CountryId = 194, CountryName = "Solomon Islands" },
                new Country { CountryId = 195, CountryName = "Seychelles" },
                new Country { CountryId = 196, CountryName = "Sudan" },
                new Country { CountryId = 197, CountryName = "Sweden" },
                new Country { CountryId = 198, CountryName = "Singapore" },
                new Country { CountryId = 199, CountryName = "Saint Helena" },
                new Country { CountryId = 200, CountryName = "Slovenia" },
                new Country { CountryId = 201, CountryName = "Svalbard and Jan Mayen" },
                new Country { CountryId = 202, CountryName = "Slovakia" },
                new Country { CountryId = 203, CountryName = "Sierra Leone" },
                new Country { CountryId = 204, CountryName = "San Marino" },
                new Country { CountryId = 205, CountryName = "Senegal" },
                new Country { CountryId = 206, CountryName = "Somalia" },
                new Country { CountryId = 207, CountryName = "Suriname" },
                new Country { CountryId = 208, CountryName = "South Sudan" },
                new Country { CountryId = 209, CountryName = "São Tomé and Príncipe" },
                new Country { CountryId = 210, CountryName = "El Salvador" },
                new Country { CountryId = 211, CountryName = "Sint Maarten" },
                new Country { CountryId = 212, CountryName = "Syria" },
                new Country { CountryId = 213, CountryName = "Eswatini" },
                new Country { CountryId = 214, CountryName = "Turks and Caicos Islands" },
                new Country { CountryId = 215, CountryName = "Chad" },
                new Country { CountryId = 216, CountryName = "French Southern Territories" },
                new Country { CountryId = 217, CountryName = "Togo" },
                new Country { CountryId = 218, CountryName = "Thailand" },
                new Country { CountryId = 219, CountryName = "Tajikistan" },
                new Country { CountryId = 220, CountryName = "Tokelau" },
                new Country { CountryId = 221, CountryName = "Timor-Leste" },
                new Country { CountryId = 222, CountryName = "Turkmenistan" },
                new Country { CountryId = 223, CountryName = "Tunisia" },
                new Country { CountryId = 224, CountryName = "Tonga" },
                new Country { CountryId = 225, CountryName = "Turkey" },
                new Country { CountryId = 226, CountryName = "Trinidad and Tobago" },
                new Country { CountryId = 227, CountryName = "Tuvalu" },
                new Country { CountryId = 228, CountryName = "Taiwan" },
                new Country { CountryId = 229, CountryName = "Tanzania" },
                new Country { CountryId = 230, CountryName = "Ukraine" },
                new Country { CountryId = 231, CountryName = "Uganda" },
                new Country { CountryId = 232, CountryName = "U.S. Outlying Islands" },
                new Country { CountryId = 233, CountryName = "United States" },
                new Country { CountryId = 234, CountryName = "Uruguay" },
                new Country { CountryId = 235, CountryName = "Uzbekistan" },
                new Country { CountryId = 236, CountryName = "Vatican City" },
                new Country { CountryId = 237, CountryName = "St Vincent and Grenadines" },
                new Country { CountryId = 238, CountryName = "Venezuela" },
                new Country { CountryId = 239, CountryName = "British Virgin Islands" },
                new Country { CountryId = 240, CountryName = "U.S. Virgin Islands" },
                new Country { CountryId = 241, CountryName = "Vietnam" },
                new Country { CountryId = 242, CountryName = "Vanuatu" },
                new Country { CountryId = 243, CountryName = "Wallis and Futuna" },
                new Country { CountryId = 244, CountryName = "Samoa" },
                new Country { CountryId = 245, CountryName = "Kosovo" },
                new Country { CountryId = 246, CountryName = "Yemen" },
                new Country { CountryId = 247, CountryName = "Mayotte" },
                new Country { CountryId = 248, CountryName = "South Africa" },
                new Country { CountryId = 249, CountryName = "Zambia" },
                new Country { CountryId = 250, CountryName = "Zimbabwe" }
            );
        }
    }
}
