// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231028125242_TestV3")]
    partial class TestV3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BusinessObject.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Affiliation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BusinessObject.AccountSpecialization", b =>
                {
                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SpecializationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConfidentLevel")
                        .HasColumnType("int");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountId", "SpecializationId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("AccountSpecializations");
                });

            modelBuilder.Entity("BusinessObject.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ArticleFileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("BusinessObject.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"), 1L, 1);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryName = "Andorra"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryName = "United Arab Emirates"
                        },
                        new
                        {
                            CountryId = 3,
                            CountryName = "Afghanistan"
                        },
                        new
                        {
                            CountryId = 4,
                            CountryName = "Antigua and Barbuda"
                        },
                        new
                        {
                            CountryId = 5,
                            CountryName = "Anguilla"
                        },
                        new
                        {
                            CountryId = 6,
                            CountryName = "Albania"
                        },
                        new
                        {
                            CountryId = 7,
                            CountryName = "Armenia"
                        },
                        new
                        {
                            CountryId = 8,
                            CountryName = "Angola"
                        },
                        new
                        {
                            CountryId = 9,
                            CountryName = "Antarctica"
                        },
                        new
                        {
                            CountryId = 10,
                            CountryName = "Argentina"
                        },
                        new
                        {
                            CountryId = 11,
                            CountryName = "American Samoa"
                        },
                        new
                        {
                            CountryId = 12,
                            CountryName = "Austria"
                        },
                        new
                        {
                            CountryId = 13,
                            CountryName = "Australia"
                        },
                        new
                        {
                            CountryId = 14,
                            CountryName = "Aruba"
                        },
                        new
                        {
                            CountryId = 15,
                            CountryName = "Åland"
                        },
                        new
                        {
                            CountryId = 16,
                            CountryName = "Azerbaijan"
                        },
                        new
                        {
                            CountryId = 17,
                            CountryName = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            CountryId = 18,
                            CountryName = "Barbados"
                        },
                        new
                        {
                            CountryId = 19,
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            CountryId = 20,
                            CountryName = "Belgium"
                        },
                        new
                        {
                            CountryId = 21,
                            CountryName = "Burkina Faso"
                        },
                        new
                        {
                            CountryId = 22,
                            CountryName = "Bulgaria"
                        },
                        new
                        {
                            CountryId = 23,
                            CountryName = "Bahrain"
                        },
                        new
                        {
                            CountryId = 24,
                            CountryName = "Burundi"
                        },
                        new
                        {
                            CountryId = 25,
                            CountryName = "Benin"
                        },
                        new
                        {
                            CountryId = 26,
                            CountryName = "Saint Barthélemy"
                        },
                        new
                        {
                            CountryId = 27,
                            CountryName = "Bermuda"
                        },
                        new
                        {
                            CountryId = 28,
                            CountryName = "Brunei"
                        },
                        new
                        {
                            CountryId = 29,
                            CountryName = "Bolivia"
                        },
                        new
                        {
                            CountryId = 30,
                            CountryName = "Bonaire, Sint Eustatius, and Saba"
                        },
                        new
                        {
                            CountryId = 31,
                            CountryName = "Brazil"
                        },
                        new
                        {
                            CountryId = 32,
                            CountryName = "Bahamas"
                        },
                        new
                        {
                            CountryId = 33,
                            CountryName = "Bhutan"
                        },
                        new
                        {
                            CountryId = 34,
                            CountryName = "Bouvet Island"
                        },
                        new
                        {
                            CountryId = 35,
                            CountryName = "Botswana"
                        },
                        new
                        {
                            CountryId = 36,
                            CountryName = "Belarus"
                        },
                        new
                        {
                            CountryId = 37,
                            CountryName = "Belize"
                        },
                        new
                        {
                            CountryId = 38,
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryId = 39,
                            CountryName = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            CountryId = 40,
                            CountryName = "DR Congo"
                        },
                        new
                        {
                            CountryId = 41,
                            CountryName = "Central African Republic"
                        },
                        new
                        {
                            CountryId = 42,
                            CountryName = "Congo Republic"
                        },
                        new
                        {
                            CountryId = 43,
                            CountryName = "Switzerland"
                        },
                        new
                        {
                            CountryId = 44,
                            CountryName = "Ivory Coast"
                        },
                        new
                        {
                            CountryId = 45,
                            CountryName = "Cook Islands"
                        },
                        new
                        {
                            CountryId = 46,
                            CountryName = "Chile"
                        },
                        new
                        {
                            CountryId = 47,
                            CountryName = "Cameroon"
                        },
                        new
                        {
                            CountryId = 48,
                            CountryName = "China"
                        },
                        new
                        {
                            CountryId = 49,
                            CountryName = "Colombia"
                        },
                        new
                        {
                            CountryId = 50,
                            CountryName = "Costa Rica"
                        },
                        new
                        {
                            CountryId = 51,
                            CountryName = "Cuba"
                        },
                        new
                        {
                            CountryId = 52,
                            CountryName = "Cabo Verde"
                        },
                        new
                        {
                            CountryId = 53,
                            CountryName = "Curaçao"
                        },
                        new
                        {
                            CountryId = 54,
                            CountryName = "Christmas Island"
                        },
                        new
                        {
                            CountryId = 55,
                            CountryName = "Cyprus"
                        },
                        new
                        {
                            CountryId = 56,
                            CountryName = "Czechia"
                        },
                        new
                        {
                            CountryId = 57,
                            CountryName = "Germany"
                        },
                        new
                        {
                            CountryId = 58,
                            CountryName = "Djibouti"
                        },
                        new
                        {
                            CountryId = 59,
                            CountryName = "Denmark"
                        },
                        new
                        {
                            CountryId = 60,
                            CountryName = "Dominica"
                        },
                        new
                        {
                            CountryId = 61,
                            CountryName = "Dominican Republic"
                        },
                        new
                        {
                            CountryId = 62,
                            CountryName = "Algeria"
                        },
                        new
                        {
                            CountryId = 63,
                            CountryName = "Ecuador"
                        },
                        new
                        {
                            CountryId = 64,
                            CountryName = "Estonia"
                        },
                        new
                        {
                            CountryId = 65,
                            CountryName = "Egypt"
                        },
                        new
                        {
                            CountryId = 66,
                            CountryName = "Western Sahara"
                        },
                        new
                        {
                            CountryId = 67,
                            CountryName = "Eritrea"
                        },
                        new
                        {
                            CountryId = 68,
                            CountryName = "Spain"
                        },
                        new
                        {
                            CountryId = 69,
                            CountryName = "Ethiopia"
                        },
                        new
                        {
                            CountryId = 70,
                            CountryName = "Finland"
                        },
                        new
                        {
                            CountryId = 71,
                            CountryName = "Fiji"
                        },
                        new
                        {
                            CountryId = 72,
                            CountryName = "Falkland Islands"
                        },
                        new
                        {
                            CountryId = 73,
                            CountryName = "Micronesia"
                        },
                        new
                        {
                            CountryId = 74,
                            CountryName = "Faroe Islands"
                        },
                        new
                        {
                            CountryId = 75,
                            CountryName = "France"
                        },
                        new
                        {
                            CountryId = 76,
                            CountryName = "Gabon"
                        },
                        new
                        {
                            CountryId = 77,
                            CountryName = "United Kingdom"
                        },
                        new
                        {
                            CountryId = 78,
                            CountryName = "Grenada"
                        },
                        new
                        {
                            CountryId = 79,
                            CountryName = "Georgia"
                        },
                        new
                        {
                            CountryId = 80,
                            CountryName = "French Guiana"
                        },
                        new
                        {
                            CountryId = 81,
                            CountryName = "Guernsey"
                        },
                        new
                        {
                            CountryId = 82,
                            CountryName = "Ghana"
                        },
                        new
                        {
                            CountryId = 83,
                            CountryName = "Gibraltar"
                        },
                        new
                        {
                            CountryId = 84,
                            CountryName = "Greenland"
                        },
                        new
                        {
                            CountryId = 85,
                            CountryName = "The Gambia"
                        },
                        new
                        {
                            CountryId = 86,
                            CountryName = "Guinea"
                        },
                        new
                        {
                            CountryId = 87,
                            CountryName = "Guadeloupe"
                        },
                        new
                        {
                            CountryId = 88,
                            CountryName = "Equatorial Guinea"
                        },
                        new
                        {
                            CountryId = 89,
                            CountryName = "Greece"
                        },
                        new
                        {
                            CountryId = 90,
                            CountryName = "South Georgia and South Sandwich Islands"
                        },
                        new
                        {
                            CountryId = 91,
                            CountryName = "Guatemala"
                        },
                        new
                        {
                            CountryId = 92,
                            CountryName = "Guam"
                        },
                        new
                        {
                            CountryId = 93,
                            CountryName = "Guinea-Bissau"
                        },
                        new
                        {
                            CountryId = 94,
                            CountryName = "Guyana"
                        },
                        new
                        {
                            CountryId = 95,
                            CountryName = "Hong Kong"
                        },
                        new
                        {
                            CountryId = 96,
                            CountryName = "Heard and McDonald Islands"
                        },
                        new
                        {
                            CountryId = 97,
                            CountryName = "Honduras"
                        },
                        new
                        {
                            CountryId = 98,
                            CountryName = "Croatia"
                        },
                        new
                        {
                            CountryId = 99,
                            CountryName = "Haiti"
                        },
                        new
                        {
                            CountryId = 100,
                            CountryName = "Hungary"
                        },
                        new
                        {
                            CountryId = 101,
                            CountryName = "Indonesia"
                        },
                        new
                        {
                            CountryId = 102,
                            CountryName = "Ireland"
                        },
                        new
                        {
                            CountryId = 103,
                            CountryName = "Israel"
                        },
                        new
                        {
                            CountryId = 104,
                            CountryName = "Isle of Man"
                        },
                        new
                        {
                            CountryId = 105,
                            CountryName = "India"
                        },
                        new
                        {
                            CountryId = 106,
                            CountryName = "British Indian Ocean Territory"
                        },
                        new
                        {
                            CountryId = 107,
                            CountryName = "Iraq"
                        },
                        new
                        {
                            CountryId = 108,
                            CountryName = "Iran"
                        },
                        new
                        {
                            CountryId = 109,
                            CountryName = "Iceland"
                        },
                        new
                        {
                            CountryId = 110,
                            CountryName = "Italy"
                        },
                        new
                        {
                            CountryId = 111,
                            CountryName = "Jersey"
                        },
                        new
                        {
                            CountryId = 112,
                            CountryName = "Jamaica"
                        },
                        new
                        {
                            CountryId = 113,
                            CountryName = "Jordan"
                        },
                        new
                        {
                            CountryId = 114,
                            CountryName = "Japan"
                        },
                        new
                        {
                            CountryId = 115,
                            CountryName = "Kenya"
                        },
                        new
                        {
                            CountryId = 116,
                            CountryName = "Kyrgyzstan"
                        },
                        new
                        {
                            CountryId = 117,
                            CountryName = "Cambodia"
                        },
                        new
                        {
                            CountryId = 118,
                            CountryName = "Kiribati"
                        },
                        new
                        {
                            CountryId = 119,
                            CountryName = "Comoros"
                        },
                        new
                        {
                            CountryId = 120,
                            CountryName = "St Kitts and Nevis"
                        },
                        new
                        {
                            CountryId = 121,
                            CountryName = "North Korea"
                        },
                        new
                        {
                            CountryId = 122,
                            CountryName = "South Korea"
                        },
                        new
                        {
                            CountryId = 123,
                            CountryName = "Kuwait"
                        },
                        new
                        {
                            CountryId = 124,
                            CountryName = "Cayman Islands"
                        },
                        new
                        {
                            CountryId = 125,
                            CountryName = "Kazakhstan"
                        },
                        new
                        {
                            CountryId = 126,
                            CountryName = "Laos"
                        },
                        new
                        {
                            CountryId = 127,
                            CountryName = "Lebanon"
                        },
                        new
                        {
                            CountryId = 128,
                            CountryName = "Saint Lucia"
                        },
                        new
                        {
                            CountryId = 129,
                            CountryName = "Liechtenstein"
                        },
                        new
                        {
                            CountryId = 130,
                            CountryName = "Sri Lanka"
                        },
                        new
                        {
                            CountryId = 131,
                            CountryName = "Liberia"
                        },
                        new
                        {
                            CountryId = 132,
                            CountryName = "Lesotho"
                        },
                        new
                        {
                            CountryId = 133,
                            CountryName = "Lithuania"
                        },
                        new
                        {
                            CountryId = 134,
                            CountryName = "Luxembourg"
                        },
                        new
                        {
                            CountryId = 135,
                            CountryName = "Latvia"
                        },
                        new
                        {
                            CountryId = 136,
                            CountryName = "Libya"
                        },
                        new
                        {
                            CountryId = 137,
                            CountryName = "Morocco"
                        },
                        new
                        {
                            CountryId = 138,
                            CountryName = "Monaco"
                        },
                        new
                        {
                            CountryId = 139,
                            CountryName = "Moldova"
                        },
                        new
                        {
                            CountryId = 140,
                            CountryName = "Montenegro"
                        },
                        new
                        {
                            CountryId = 141,
                            CountryName = "Saint Martin"
                        },
                        new
                        {
                            CountryId = 142,
                            CountryName = "Madagascar"
                        },
                        new
                        {
                            CountryId = 143,
                            CountryName = "Marshall Islands"
                        },
                        new
                        {
                            CountryId = 144,
                            CountryName = "North Macedonia"
                        },
                        new
                        {
                            CountryId = 145,
                            CountryName = "Mali"
                        },
                        new
                        {
                            CountryId = 146,
                            CountryName = "Myanmar"
                        },
                        new
                        {
                            CountryId = 147,
                            CountryName = "Mongolia"
                        },
                        new
                        {
                            CountryId = 148,
                            CountryName = "Macao"
                        },
                        new
                        {
                            CountryId = 149,
                            CountryName = "Northern Mariana Islands"
                        },
                        new
                        {
                            CountryId = 150,
                            CountryName = "Martinique"
                        },
                        new
                        {
                            CountryId = 151,
                            CountryName = "Mauritania"
                        },
                        new
                        {
                            CountryId = 152,
                            CountryName = "Montserrat"
                        },
                        new
                        {
                            CountryId = 153,
                            CountryName = "Malta"
                        },
                        new
                        {
                            CountryId = 154,
                            CountryName = "Mauritius"
                        },
                        new
                        {
                            CountryId = 155,
                            CountryName = "Maldives"
                        },
                        new
                        {
                            CountryId = 156,
                            CountryName = "Malawi"
                        },
                        new
                        {
                            CountryId = 157,
                            CountryName = "Mexico"
                        },
                        new
                        {
                            CountryId = 158,
                            CountryName = "Malaysia"
                        },
                        new
                        {
                            CountryId = 159,
                            CountryName = "Mozambique"
                        },
                        new
                        {
                            CountryId = 160,
                            CountryName = "Namibia"
                        },
                        new
                        {
                            CountryId = 161,
                            CountryName = "New Caledonia"
                        },
                        new
                        {
                            CountryId = 162,
                            CountryName = "Niger"
                        },
                        new
                        {
                            CountryId = 163,
                            CountryName = "Norfolk Island"
                        },
                        new
                        {
                            CountryId = 164,
                            CountryName = "Nigeria"
                        },
                        new
                        {
                            CountryId = 165,
                            CountryName = "Nicaragua"
                        },
                        new
                        {
                            CountryId = 166,
                            CountryName = "Netherlands"
                        },
                        new
                        {
                            CountryId = 167,
                            CountryName = "Norway"
                        },
                        new
                        {
                            CountryId = 168,
                            CountryName = "Nepal"
                        },
                        new
                        {
                            CountryId = 169,
                            CountryName = "Nauru"
                        },
                        new
                        {
                            CountryId = 170,
                            CountryName = "Niue"
                        },
                        new
                        {
                            CountryId = 171,
                            CountryName = "New Zealand"
                        },
                        new
                        {
                            CountryId = 172,
                            CountryName = "Oman"
                        },
                        new
                        {
                            CountryId = 173,
                            CountryName = "Panama"
                        },
                        new
                        {
                            CountryId = 174,
                            CountryName = "Peru"
                        },
                        new
                        {
                            CountryId = 175,
                            CountryName = "French Polynesia"
                        },
                        new
                        {
                            CountryId = 176,
                            CountryName = "Papua New Guinea"
                        },
                        new
                        {
                            CountryId = 177,
                            CountryName = "Philippines"
                        },
                        new
                        {
                            CountryId = 178,
                            CountryName = "Pakistan"
                        },
                        new
                        {
                            CountryId = 179,
                            CountryName = "Poland"
                        },
                        new
                        {
                            CountryId = 180,
                            CountryName = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            CountryId = 181,
                            CountryName = "Pitcairn Islands"
                        },
                        new
                        {
                            CountryId = 182,
                            CountryName = "Puerto Rico"
                        },
                        new
                        {
                            CountryId = 183,
                            CountryName = "Palestine"
                        },
                        new
                        {
                            CountryId = 184,
                            CountryName = "Portugal"
                        },
                        new
                        {
                            CountryId = 185,
                            CountryName = "Palau"
                        },
                        new
                        {
                            CountryId = 186,
                            CountryName = "Paraguay"
                        },
                        new
                        {
                            CountryId = 187,
                            CountryName = "Qatar"
                        },
                        new
                        {
                            CountryId = 188,
                            CountryName = "Réunion"
                        },
                        new
                        {
                            CountryId = 189,
                            CountryName = "Romania"
                        },
                        new
                        {
                            CountryId = 190,
                            CountryName = "Serbia"
                        },
                        new
                        {
                            CountryId = 191,
                            CountryName = "Russia"
                        },
                        new
                        {
                            CountryId = 192,
                            CountryName = "Rwanda"
                        },
                        new
                        {
                            CountryId = 193,
                            CountryName = "Saudi Arabia"
                        },
                        new
                        {
                            CountryId = 194,
                            CountryName = "Solomon Islands"
                        },
                        new
                        {
                            CountryId = 195,
                            CountryName = "Seychelles"
                        },
                        new
                        {
                            CountryId = 196,
                            CountryName = "Sudan"
                        },
                        new
                        {
                            CountryId = 197,
                            CountryName = "Sweden"
                        },
                        new
                        {
                            CountryId = 198,
                            CountryName = "Singapore"
                        },
                        new
                        {
                            CountryId = 199,
                            CountryName = "Saint Helena"
                        },
                        new
                        {
                            CountryId = 200,
                            CountryName = "Slovenia"
                        },
                        new
                        {
                            CountryId = 201,
                            CountryName = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            CountryId = 202,
                            CountryName = "Slovakia"
                        },
                        new
                        {
                            CountryId = 203,
                            CountryName = "Sierra Leone"
                        },
                        new
                        {
                            CountryId = 204,
                            CountryName = "San Marino"
                        },
                        new
                        {
                            CountryId = 205,
                            CountryName = "Senegal"
                        },
                        new
                        {
                            CountryId = 206,
                            CountryName = "Somalia"
                        },
                        new
                        {
                            CountryId = 207,
                            CountryName = "Suriname"
                        },
                        new
                        {
                            CountryId = 208,
                            CountryName = "South Sudan"
                        },
                        new
                        {
                            CountryId = 209,
                            CountryName = "São Tomé and Príncipe"
                        },
                        new
                        {
                            CountryId = 210,
                            CountryName = "El Salvador"
                        },
                        new
                        {
                            CountryId = 211,
                            CountryName = "Sint Maarten"
                        },
                        new
                        {
                            CountryId = 212,
                            CountryName = "Syria"
                        },
                        new
                        {
                            CountryId = 213,
                            CountryName = "Eswatini"
                        },
                        new
                        {
                            CountryId = 214,
                            CountryName = "Turks and Caicos Islands"
                        },
                        new
                        {
                            CountryId = 215,
                            CountryName = "Chad"
                        },
                        new
                        {
                            CountryId = 216,
                            CountryName = "French Southern Territories"
                        },
                        new
                        {
                            CountryId = 217,
                            CountryName = "Togo"
                        },
                        new
                        {
                            CountryId = 218,
                            CountryName = "Thailand"
                        },
                        new
                        {
                            CountryId = 219,
                            CountryName = "Tajikistan"
                        },
                        new
                        {
                            CountryId = 220,
                            CountryName = "Tokelau"
                        },
                        new
                        {
                            CountryId = 221,
                            CountryName = "Timor-Leste"
                        },
                        new
                        {
                            CountryId = 222,
                            CountryName = "Turkmenistan"
                        },
                        new
                        {
                            CountryId = 223,
                            CountryName = "Tunisia"
                        },
                        new
                        {
                            CountryId = 224,
                            CountryName = "Tonga"
                        },
                        new
                        {
                            CountryId = 225,
                            CountryName = "Turkey"
                        },
                        new
                        {
                            CountryId = 226,
                            CountryName = "Trinidad and Tobago"
                        },
                        new
                        {
                            CountryId = 227,
                            CountryName = "Tuvalu"
                        },
                        new
                        {
                            CountryId = 228,
                            CountryName = "Taiwan"
                        },
                        new
                        {
                            CountryId = 229,
                            CountryName = "Tanzania"
                        },
                        new
                        {
                            CountryId = 230,
                            CountryName = "Ukraine"
                        },
                        new
                        {
                            CountryId = 231,
                            CountryName = "Uganda"
                        },
                        new
                        {
                            CountryId = 232,
                            CountryName = "U.S. Outlying Islands"
                        },
                        new
                        {
                            CountryId = 233,
                            CountryName = "United States"
                        },
                        new
                        {
                            CountryId = 234,
                            CountryName = "Uruguay"
                        },
                        new
                        {
                            CountryId = 235,
                            CountryName = "Uzbekistan"
                        },
                        new
                        {
                            CountryId = 236,
                            CountryName = "Vatican City"
                        },
                        new
                        {
                            CountryId = 237,
                            CountryName = "St Vincent and Grenadines"
                        },
                        new
                        {
                            CountryId = 238,
                            CountryName = "Venezuela"
                        },
                        new
                        {
                            CountryId = 239,
                            CountryName = "British Virgin Islands"
                        },
                        new
                        {
                            CountryId = 240,
                            CountryName = "U.S. Virgin Islands"
                        },
                        new
                        {
                            CountryId = 241,
                            CountryName = "Vietnam"
                        },
                        new
                        {
                            CountryId = 242,
                            CountryName = "Vanuatu"
                        },
                        new
                        {
                            CountryId = 243,
                            CountryName = "Wallis and Futuna"
                        },
                        new
                        {
                            CountryId = 244,
                            CountryName = "Samoa"
                        },
                        new
                        {
                            CountryId = 245,
                            CountryName = "Kosovo"
                        },
                        new
                        {
                            CountryId = 246,
                            CountryName = "Yemen"
                        },
                        new
                        {
                            CountryId = 247,
                            CountryName = "Mayotte"
                        },
                        new
                        {
                            CountryId = 248,
                            CountryName = "South Africa"
                        },
                        new
                        {
                            CountryId = 249,
                            CountryName = "Zambia"
                        },
                        new
                        {
                            CountryId = 250,
                            CountryName = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("BusinessObject.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRelease")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Volumn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Issue");
                });

            modelBuilder.Entity("BusinessObject.Major", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MajorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Majors");
                });

            modelBuilder.Entity("BusinessObject.RequestDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RequestReviewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RequestReviewId");

                    b.ToTable("RequestDetails");
                });

            modelBuilder.Entity("BusinessObject.RequestReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("RequestReviews");
                });

            modelBuilder.Entity("BusinessObject.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("Rolename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Rolename = "Director"
                        },
                        new
                        {
                            RoleId = 2,
                            Rolename = "Staff"
                        },
                        new
                        {
                            RoleId = 3,
                            Rolename = "Reviewer"
                        },
                        new
                        {
                            RoleId = 4,
                            Rolename = "Author"
                        },
                        new
                        {
                            RoleId = 5,
                            Rolename = "User"
                        });
                });

            modelBuilder.Entity("BusinessObject.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MajorId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModificationBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecializationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MajorId");

                    b.ToTable("Specializations");
                });

            modelBuilder.Entity("BusinessObject.Account", b =>
                {
                    b.HasOne("BusinessObject.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObject.AccountSpecialization", b =>
                {
                    b.HasOne("BusinessObject.Account", "Account")
                        .WithMany("Specializations")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Specialization", "Specialization")
                        .WithMany("AccountSpecializations")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("BusinessObject.Article", b =>
                {
                    b.HasOne("BusinessObject.Issue", "Issue")
                        .WithMany("Articles")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("BusinessObject.RequestDetail", b =>
                {
                    b.HasOne("BusinessObject.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("BusinessObject.RequestReview", "RequestReview")
                        .WithMany("Details")
                        .HasForeignKey("RequestReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("RequestReview");
                });

            modelBuilder.Entity("BusinessObject.RequestReview", b =>
                {
                    b.HasOne("BusinessObject.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("BusinessObject.Specialization", b =>
                {
                    b.HasOne("BusinessObject.Major", "Major")
                        .WithMany("Specializations")
                        .HasForeignKey("MajorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Major");
                });

            modelBuilder.Entity("BusinessObject.Account", b =>
                {
                    b.Navigation("Specializations");
                });

            modelBuilder.Entity("BusinessObject.Issue", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("BusinessObject.Major", b =>
                {
                    b.Navigation("Specializations");
                });

            modelBuilder.Entity("BusinessObject.RequestReview", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("BusinessObject.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("BusinessObject.Specialization", b =>
                {
                    b.Navigation("AccountSpecializations");
                });
#pragma warning restore 612, 618
        }
    }
}
